#spring.application.name=diagram-generator
#spring.ai.openai.api-key=AIzaSyB71Maf4ReM-_ChorC_T_FH-lrFt_Xunnc
#
#spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
#
#spring.ai.openai.chat.options.model=gemini-2.0-flash-lite
#
#spring.ai.retry.max-attempts=1

spring.application.name=diagram-generator
#spring.ai.openai.api-key=AIzaSyB71Maf4ReM-_ChorC_T_FH-lrFt_Xunnc
spring.ai.openai.chat.options.model=gemini-1.5-flash
spring.ai.retry.max-attempts=1
spring.ai.openai.api-key=dummy
gemini.api.key=AIzaSyD5URedZjp0JKbd0o5LAPQHkcEV3-LCv40